version: "3.9"
   
services:
  jobmanager:
    # This is (roughly) the version of Flink supported by EMR
    image: flink:1.12.5-scala_2.11-java11
    command: "jobmanager.sh start-foreground"
    ports:
      - 8081:8081
    restart: always
    volumes:
      - ./conf:/opt/flink/conf
      - /tmp/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: flink:1.12.5-scala_2.11-java11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    restart: always
    volumes:
      - ./conf:/opt/flink/conf
      - /tmp/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  console:
    build:
      context: ./
      dockerfile: Dockerfile-console
    container_name: console
    command: flink -v # Service is meant for ssh, so we don't want it to actually boot
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./app:/app
      - ./conf:/opt/flink/conf
      - ./.m2:/root/.m2

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_HOST_NAME=kafka
