FROM flink:1.12.5-scala_2.11-java11
FROM maven:3.8-jdk-11
COPY --from=0 /opt/flink /opt/flink
ENV PATH=/opt/flink/bin:$PATH

RUN set -ex; \
  apt-get update; \
  apt-get -y install xmlstarlet; \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app
